/**
 * Auto-generated by scripts/set-env.mjs from the .env file.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 * Edit .env and run `npm start` or `npm run build` to regenerate.
 */

export const environment = {
  production: true,
  apiBaseUrl: 'https://localhost:7296/api',
};
