import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function loadEnvFile() {
  const env = {};
  const envPath = resolve(root, '.env');

  if (!existsSync(envPath)) {
    return env;
  }

  const content = readFileSync(envPath, 'utf8');

  for (const rawLine of content.split(/\r?\n/)) {
    const line = rawLine.trim();

    if (!line || line.startsWith('#')) {
      continue;
    }

    const eq = line.indexOf('=');

    if (eq === -1) {
      continue;
    }

    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();

    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    if (key) {
      env[key] = value;
    }
  }

  return env;
}

const env = loadEnvFile();
const apiBaseUrl = env.API_URL || 'http://localhost:5000/api';
const devApiBaseUrl = env.API_URL_DEV || apiBaseUrl;
const proxyTarget = env.PROXY_TARGET || apiBaseUrl;

const header = `/**
 * Auto-generated by scripts/set-env.mjs from the .env file.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 * Edit .env and run \`npm start\` or \`npm run build\` to regenerate.
 */`;

function generateFile(fileName, isProduction, baseUrl) {
  const content = `${header}

export const environment = {
  production: ${isProduction ? 'true' : 'false'},
  apiBaseUrl: '${baseUrl}',
};
`;

  writeFileSync(resolve(root, fileName), content);
}

generateFile('src/environments/environment.ts', true, apiBaseUrl);
generateFile('src/environments/environment.development.ts', false, devApiBaseUrl);

const proxyConfig = {
  '/api': {
    target: proxyTarget,
    secure: false,
    changeOrigin: true,
  },
};

writeFileSync(resolve(root, 'proxy.conf.json'), `${JSON.stringify(proxyConfig, null, 2)}\n`);

console.log(`[set-env] Generated environment files. prod=${apiBaseUrl} dev=${devApiBaseUrl} proxyTarget=${proxyTarget}`);
